<?php

function servicebot_test_servicebot_customer_subscription_created($stripe_subscription_object) {
  $f = 0;
}

function servicebot_test_servicebot_customer_subscription_updated($stripe_subscription_object) {
  $f = 0;
}

function servicebot_test_servicebot_customer_subscription_deleted($stripe_subscription_object) {
  $f = 0;
}

function servicebot_test_servicebot_customer_source_created($stripe_subscription_object) {
  $f = 0;
}

function servicebot_test_servicebot_customer_source_updated($stripe_subscription_object) {
  $f = 0;
}

function servicebot_test_servicebot_customer_source_expiring($stripe_subscription_object) {
  $f = 0;
}

function servicebot_test_servicebot_customer_subscription_trial_will_end($stripe_subscription_object) {
  $f = 0;
}

function servicebot_test_servicebot_invoice_payment_failed($stripe_invoice_object) {
  $f = 0;
}

